robocup-logistics/rcll-refbox

- .circleci/config.yml
- src/libs/mongodb_log/mongodb.mk
Update to the latest Ubuntu LTS, install the missing package `libmongoclient-dev` into the Ubuntu environment, and fix an error that caused underlinking on Ubuntu.
This fixes #11.
> Update to Ubuntu Bionic, fix mongodb support on Ubuntu

- .circleci/config.yml
- etc/buildsys/base.mk
- etc/buildsys/rules.mk
- src/refbox/Makefile
This adds an option to fail if any warning occurred, which is enabled by calling `make FAIL_ON_WARNING=1`.
Enable the option in all circleci build to avoid silent regressions.
> circleci: fail if a warning occurs during build

- src/games/rcll/production.clp
- src/msgs/MachineInstructions.proto
- src/shell/machine.cpp
- src/tools/rcll-prepare-machine.cpp
Remove the gate from the prepare message of the delivery station. When processing the message, get the correct gate from the respective order fact instead. If no order exists for the order ID given in the prepare message, set the DS to broken.
In the shell, display the order ID instead of the gate, which is more useful information anyway.
Also adapt the `rcll-prepare-machine` tool accordingly.
This implements robocup-logistics/rcll-rulebook#21.
> Remove gate from DS prepare msg

- src/libs/mps_placing_clips/mps_placing.h
According to the 2019 rulebook, both input and output side
need to be blocked for storing stations.
> Block input and output for SS

- src/libs/mps_comm/machine.cpp
- src/refbox/refbox.cpp
In preparation for #15 and #30, register a callback for the barcode and assert a CLIPS fact.
This assumes the barcode to be a `int32`, which may need to be fixed in the PLC code, where it's handled inconsistently (as string and int).
> Register callback to read the barcode from the MPS

- src/refbox/Makefile
- src/refbox/refbox.h
Those changes were needed for me to be able to build the refbox. 
- Fix, check for and include freeopcua build flags in refbox MakeFile
- Include <future> lib as my compiler (gcc 7) did not identify it as a member of std.
> Small build fixes

- Dockerfile
- cfg/config.yaml
- etc/buildsys/config.mk
- src/libs/core/threading/thread.cpp
- src/libs/netcomm/Makefile
- src/libs/netcomm/netcomm.mk
- src/refbox/refbox.cpp
Create a docker image that contains the refbox. In particular:
* Use [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) to make the image as minimal as possible.
* Compute the dependencies from the built libraries and binaries to
1. Avoid duplication of the list of packages to be installed
1. Only install those dependencies that are actually needed.
This reduces the size of the image considerably.
* Add a build flag to disable avahi support. Avahi currently does not work in a container, at least not in the way that we use it (it results in 100% CPU load). Build the docker image without avahi, the rest with avahi.
* Allow a different location for CLIPS and protobuf msgs files. These are installed in `/usr/local/share` in the resulting image, but they …
> Provide a docker image

- src/games/rcll/workpieces.clp
We should not assume that the individual production steps happened at
the same time as the delivery, as this results in no points given if the
delivery is late. Instead, if we are not tracking, simply assume that
all steps happened at time 0.1 to guarantee that they are before the
delivery deadline. This restores the old behavior of giving full points
for production steps, even if the delivery is late.
> rcll: give full production steps in failsafe for late delivery

- src/games/rcll/orders.clp
If a cap is mounted after the delivery deadline, the cap mount is
silently ignored, leading to confusion. Thus, be more verbose by
explicitly giving 0 points for the operation, which will show up in the
log. Also print the reason and the delivery deadline.
This resolves #42, which was not actually a bug, because the cap was in fact mounted after the delivery deadline.
> Be more verbose about late cap mounts

- src/games/rcll/production.clp
We sometimes miss workpieces and then disable the tracking completely
for the whole game. Instead of doing this, do not set the machine to
READY-AT-OUTPUT if it did not see a workpiece and the tracking is
enabled. This allows the referee and or the machine to recover, either
by manually moving the workpiece into the barcode scanner, or by moving
the belt.
> Only set MPS to READY-AT-OUTPUT if workpiece has been seen

- src/shell/shell.cpp
The new boost version expects a long int as constructor argument for all
boost::posix_time objects. Cast the time to a long int and construct it
as milliseconds to keep the resolution.
This fixes #49.
> Adapt to boost::posix_time expecting long ints, not floats

- cfg/config.yaml
- src/games/rcll/workpieces.clp
If tracking is enabled and the MPS already processed the workpiece but has not seen a barcode yet, print a warning, as this is usually either a problem with the barcode scanner or a misconfiguration.
Also disable tracking by default, as the default config is supposed to work in simulation.
> Warn if an MPS is waiting for workpiece tracking

- etc/buildsys/gcc.mk
- src/libs/mps_comm/machine.cpp
- src/libs/mps_comm/mps_comm.mk
* Correctly detect the currently supported C++11 standard and set `CFLAGS_CPP11` and `CFLAGS_CPP14` accordingly
* Build `libmps_comm` with `CFLAGS_CPP11`, which is required by freeopcua
* Do not use `std::chrono_literals` as those require C++14
This fixes build errors on older systems, in particular Ubuntu 16.04. While we do not support such old distributions, these fixes are straight forward and make sense generally.
> Adapt mps_comm to use correct c++11 build flags, do not require c++14

- src/games/rcll/production.clp
If an MPS goes down while it is `PREPARED` or `PROCESSING`, delay the respective timeout by the down time. Otherwise, the machine breaks immediately after coming back, as the timeout will fire, giving the team no opportunity to feed a product into the machine.
There are two cases that need to be handled:
1. The machine is `PREPARED` when going `DOWN`, i.e., we received a prepare message but there is no workpiece yet. Delay the timeout so the team has additional time after the machine is available again.
2. The machine is already `PROCESSING` or `PROCESSED`. In this case, the processing timeout needs to be delayed.
Along the way, fix the indentation for prepare message handling. If you want to ignore the space change, use `git diff --ignore-space-change`.
This fixes #6.
> Account for down time in preparation timeout

- .circleci/config.yml
- Dockerfile
- cfg/config.yaml
- src/games/rcll/mongodb.clp
- src/libs/mongodb_log/Makefile
- src/libs/mongodb_log/mongodb.mk
- src/libs/mongodb_log/mongodb_log_logger.cpp
- src/libs/mongodb_log/mongodb_log_logger.h
- src/libs/mongodb_log/mongodb_log_protobuf.cpp
- src/libs/mongodb_log/mongodb_log_protobuf.h
- src/refbox/Makefile
- src/refbox/main.cpp
- src/refbox/refbox.cpp
- src/refbox/refbox.h
Switch from the legacy mongocxx driver to the most recent mongocxx-v3. In particular:
* Adapt the mongodb logger
* Adapt the provided CLIPS functions to use mongocxx-v3
There are some changes that were necessary because the new mongocxx provides a different API:
* We need to distinguish `bsoncxx::document::value` (among others, the result of a query) and `bsoncxx::builder::basic::document` (used to create new documents). Thus, there are now two separate functions in CLIPS to delete a document: `bson-builder-destroy` to destroy a `bsoncxx::builder::basic::document` and `bson-destroy` to destroy a `bsoncxx::document::value`.
* Array building is slightly different. Instead of directly attaching the array to a document, create the array, then add it as a sub-document of an existing doc.
> Switch to mongocxx v3

- src/libs/config/config.cpp
- src/libs/config/config.h
- src/libs/config/config.mk
- src/libs/config/yaml.cpp
- src/libs/config/yaml.h
- src/libs/config/yaml_node.h
- src/libs/utils/misc/string_compare.cpp
- src/libs/utils/misc/string_compare.h
- src/libs/utils/misc/string_conversions.cpp
- src/libs/utils/misc/string_conversions.h
- src/libs/utils/misc/string_split.h
The config parser lib was originally taken from fawkes. Since then, various improvements to the parser were made in the fakes repository. In an attempt to bring those changes to this repo, i simply copied the files over and adapted them to the refbox namespace.
However, since i did not want to introduce unused features that would effectively act as dead code, i refrained from also copying related utility libs or dependencies that are used on fawkes side but are not part of the refbox repo, as of yet.
Hence, this PR does not add new files, it rather just updates the yaml config lib and the `libs/utils/misc/` lib files. The build process and dependencies remain untouched.
As a consequence, some advanced features available in fawkes are not carried over, yet.
My intentions for this PR were …
> update config parser lib according to changes in the fawkes repo

- src/libs/netcomm/dns-sd/avahi_thread.cpp
- src/libs/netcomm/dns-sd/avahi_thread.h
Sometimes, creating a client fails, e.g., if the daemon is not
available. In that case, instead of directly trying again in the next
iteration, let the thread sleep for a while. This avoids the thread to
run on 100% CPU because it continuously tries re-creating the client.
This fixes #67.
> netcomm: let avahi thread sleep for a while if creating a client fails

- src/tools/rcll-refbox-instruct.cpp
Sometimes, we may want to wait for robots, e.g., when running in
simulation. Instead of guessing how long the robots need to connect,
extend the rcll-refbox-instruct tool to wait for some given number of
robots. This also works in conjunction with the other wait options,
e.g., waiting for a game phase.
Example usage:
```
$ ./rcll-refbox-instruct -n2 -W -p PRODUCTION
```
This will wait for two robots to appear, as well as for the phase to switch to PRODUCTION.
> Extend rcll-refbox-instruct to wait for a given number of robots

- cfg/config.yaml
- src/games/rcll/config.clp
- src/games/rcll/game.clp
- src/games/rcll/production.clp
This PR deals with an issue that occurs, whenever a ring station should be simulated logically (e.g., when a RS is physically broken, has empty batteries or a malfunctioning slide counter sensor).
**Status Quo:** It is already possible to simulate all other machines logically without further work from the refbox operator, because usual machine interactions are in the form of instructions that can be processed in the refbox, skipping the machine-sided communication. Field referees may move the workpieces around, such that games can be played out normally.
Ring stations have the distinct feature of a one-sided feedback from the machine to the refbox, whenever a payment at the slide is registered. Since no instructions from the acting robot is sent in that case, it currently requires a …
> add configurable refbox-sided ring-payment feedbacks

- cfg/config.yaml
- src/games/rcll/facts.clp
- src/games/rcll/game.clp
- src/games/rcll/simulation.clp
- src/libs/Makefile
- src/libs/mps_comm/Makefile
- src/libs/mps_comm/mockup/base_station.cpp
- src/libs/mps_comm/mockup/cap_station.cpp
- src/libs/mps_comm/mockup/delivery_station.cpp
- src/libs/mps_comm/mockup/machine.cpp
- src/libs/mps_comm/mockup/machine.h
- src/libs/mps_comm/mockup/ring_station.cpp
This PR adds a configurable speedup factor that does two things:
1. Scaling of individual mockup mps instruction times and
2. scaling of the game-time updates by the given factor
This allows to simulate games faster than real-time while staying close to an actual regular-paced game, given that the participating robots are sped up accordingly.
One may be at risk of having mps states that move too fast to be observable. I set the minimal instruction time per command to one second (2 seconds in case of the delivery station) and it worked well on my laptop across multiple games (tested >10 games). 
This also means that the relation between machine instruction times and the corresponding elapsing in-game seconds will drift apart ("machine instructions take relatively way longer") the higher …
> Accelerate games in simulation

- etc/buildsys/gcc.mk
- src/libs/mps_comm/Makefile
- src/libs/mps_comm/machine_factory.cpp
- src/libs/mps_comm/mockup/base_station.cpp
- src/libs/mps_comm/mockup/cap_station.cpp
- src/libs/mps_comm/mockup/delivery_station.cpp
- src/libs/mps_comm/mockup/durations.h
- src/libs/mps_comm/mockup/machine.cpp
- src/libs/mps_comm/mockup/ring_station.cpp
* Move all durations into a separate file so they can be easier checked and modified
* Use measurements from our lab for the mockup durations (thanks to @lyndwyrm666 for the data)
> Use realistic durations for MPS mockup operations

- src/libs/mps_comm/opcua/machine.cpp
Add missing includes of spdlog sinks.
Those became necessary by a recent freeopcua update, which uses the system spdlog instead of bundling it. Those files were previously included from the freeopcua headers.
Conditionalize the include on `HAVE_SYSTEM_SPDLOG` to stay compatible with the old version of freeopcua.
> Adapt to freeopcua with system spdlog

- .circleci/config.yml
- Dockerfile
- src/libs/mps_comm/Makefile
- src/libs/mps_comm/freeopcua.mk
- src/libs/mps_comm/spdlog.mk
Fedora now has an [official freeopcua package](https://bugzilla.redhat.com/show_bug.cgi?id=1824467). Use that package instead of the COPR.
Also adapt the build system so it properly checks for freeopcua and spdlog. This resolves a small complication with freeopcua: The package may be built either using a bundled spdlog or a system installation of spdlog. Furthermore, spdlog may in turn ship a bundled libfmt or use the system libfmt. If freeopcua uses the system spdlog, then we also need to check for the package being available and also use its build flags. Otherwise, we just use the build flags of freeopcua.
> Use the official Fedora package for freeopcua

- .circleci/config.yml
- etc/format-scripts/check-branch-files.sh
- etc/format-scripts/env.sh
Until now, `make quick-check` did not spot misformated files, because `diff` was not installed in the CI environment. Extend the formatting scripts to explicitly check for all needed tools and also install diff in the CI environment.
> Make sure all tools for the formatting checks are installed

- src/libs/webview/request.cpp
- src/libs/webview/request_dispatcher.cpp
- src/libs/webview/request_dispatcher.h
The microhttpd lib introduced an enum `MHD_Result` instead of passing results via integers.
Note that they were a bit inconsistent as
`MHD_queue_basic_auth_fail_response` still returns int, which is caught
via static cast to the enum.
Edit: this also mentioned in #82.
This fixes #82.
> webview: adapt to MHD_Result enum

- src/games/rcll/mongodb.clp
> rcll: convert ring colors to symbols when loading from mongodb

- Dockerfile
- src/libs/websocket/data.cpp
This PR fixes #89 by using the right environment variable for addressing the message schemas and updating the Dockerfile to move the schemas accordingly.
While at it, i also removed all the trailing whitespace errors within the websocket data.cpp
> fix docker build failure caused by missing websocket message schemas

- src/libs/logging/llsf_log_msgs/LogMessage.proto
- src/libs/mps_placing_clips/mps_placing.h
- src/libs/protobuf_clips/communicator.cpp
- src/libs/rest-api/Makefile
- src/libs/webview/Makefile
- src/libs/webview/webview.mk
- src/refbox/Makefile
- src/refbox/refbox.cpp
- src/shell/shell.cpp
gecode 6 changed its API. Adapt accordingly, but keep backwards compatibility.
boost 1.73 deprecates global placeholders. Adapt by
* avoiding the use of global placeholders (use `boost/bind/bind.hpp` instead of `boost/bind.hpp`)
* using the placeholders namespace where necessary
* disabling the deprecation warning where we include external headers which trigger the warning
> Adapt to boost 1.73 and gecode 6 (Fedora 33)

- src/libs/protobuf_clips/communicator.cpp
- src/libs/protobuf_clips/communicator.h
A combination of an uninitialized `long int` client id and its conversion to an `unsigned int` before asserting the corresponding protobuf clips fact can potentially lead to broken client ids in clips. Avoid this by sticking to `long int` and initializing the client id increment value.
> fix inconsistent protobuf client ids

- src/libs/mps_comm/opcua/machine.cpp
- src/libs/utils/time/time.cpp
- src/shell/Makefile
- src/shell/robot.cpp
- src/shell/shell.cpp
When compiled with distro build flags (`make  CFLAGS_EXTRA="$(rpm --eval '%{optflags}')"`), the compiler would give some additional warnings and errors. Fix those warnings as they may all be real issues.
> Fix Fedora 33 compiler warnings

- cfg/config.yaml
- src/games/rcll/facts.clp
- src/games/rcll/game.clp
- src/games/rcll/machines.clp
- src/games/rcll/mongodb.clp
- src/games/rcll/utils.clp
This PR reworks the mongodb usage to store and retrieve data in game reports.
- It introduces new configurable options to de-randomize games using data stored in old reports, which can be beneficial to create reproducible benchmarks.
- More data is captured in game reports (such as a history of all machine state changes). This creates a common data-format to evaluate performances of different runs. Future PRs will provide some scripts to evaluate the data automatically for some key criteria 
- This PR also provides generic functions to store/retrieve any fact from/to a game-report and thereby allows to easily extend the functionalities in the future
> rework storage and retrieval of mongodb game reports

- src/libs/core/threading/thread.cpp
- src/refbox/refbox.cpp
This adds minor changes required to be able to build in Fedora 35 (using `glibc >= 2.34`).
> Fix build issues in Fedora 35

- src/games/rcll/mongodb.clp
- src/libs/protobuf_clips/communicator.h
Restoring the total points directly does not work, because they get overwritten periodically and are not persistent. This PR creates a new points fact (just like when scoring in the game) with reason "restored" when the game is loaded from a gamereport. The points are taken from the phasepoints in the gamereport.
> Restore phase points from gamereport

- src/games/rcll/exploration.clp
- src/games/rcll/facts.clp
- src/games/rcll/game.clp
- src/games/rcll/globals.clp
- src/games/rcll/machine-lights.clp
- src/games/rcll/machines.clp
- src/games/rcll/production.clp
- src/msgs/MachineReport.proto
- src/tools/llsf-report-machine.cpp
This PR implements the changes required for https://github.com/robocup-logistics/rcll-rulebook/pull/50 and should be merged only if the rule changes are accepted.
It takes care about 2 major things:
If a team decides to play without AR Tags, then they need to be able to report machines based on the type, zone and rotation. This will be possible through minor changes to the MachineReport messages:
1. The name is not a required field anymore in the reported machine, instead a type might be provided. https://github.com/robocup-logistics/rcll-refbox/blob/bdd9069416f460f022a048e32efe58916bade4f0/src/msgs/MachineReport.proto#L54-L59
2. The MachineReportInfo that is returned will now contain feedback about a machine name and the belonging team, if a report with a correct type + zone was received …
> combine exploration and production phase and support markerless gameplay

- cfg/challenges/grasping/grasping_game.yaml
- cfg/game/default_game.yaml
- cfg/game/load_field_layout.yaml
- cfg/game/load_game.yaml
- src/games/rcll/facts.clp
- src/games/rcll/game.clp
- src/games/rcll/machines.clp
- src/games/rcll/mongodb.clp
This implements changes discussed in https://github.com/robocup-logistics/rcll-rulebook/pull/54 and should only be merged once that PR is merged.
It is noteworthy that this renames one config value, namely `llsfrb/game/random-storage` to `llsfrb/game/default-storage`.
> Remove useless randomization

- cfg/game/default_game.yaml
- cfg/game/load_field_layout.yaml
- cfg/game/load_game.yaml
- src/games/rcll/globals.clp
- src/games/rcll/production.clp
Useful for debugging, also adds a printout to indicate when the exploration time is over.
> Make exploration time configurable

- src/games/rcll/exploration.clp
- src/games/rcll/production.clp
I noticed that the ground-truth settings of the challenge configs was effectively not proessed anymore (due to https://github.com/robocup-logistics/rcll-refbox/pull/120). This PR addresses that issue.
> fix ground truth in challenges

- .circleci/config.yml
- Dockerfile
- etc/buildsys/clips.mk
- src/games/rcll/game.clp
- src/libs/rest-api/clips-rest-api/clips-rest-api.cpp
- src/refbox/clips_logger.cpp
This PR updates the used clips version to the latest 6.3x revision. The required packages are provided through a copr from fedora onwards. Circle-ci and Docker container are updated as well.
Due to changes in the new clang-format version it is required to do a full source tree format, which is also included in this PR.
> Update to latest clips 63x

- etc/scripts/generate_benchmarks.bash
As the refbox now uses a modular configuration loading process, the benchmark generator script should use that as well.
> adapt benchmark generator script to refbox changes

- src/games/rcll/net.clp
- src/games/rcll/production.clp
In fast simulations it can happen that states change so quickly, that they are never broadcasted to the teams.
To avoid issues, simple also broadcast whenever a state change happens.
This PR is based on https://github.com/robocup-logistics/rcll-refbox/pull/135 and its base needs to switched to the master before opening it for review.
> Ensure mps state changes are always broadcasted

- cfg/comm/default_comm.yaml
- src/games/rcll/game.clp
- src/games/rcll/init.clp
- src/games/rcll/mongodb.clp
- src/games/rcll/net.clp
- src/games/rcll/websocket.clp
- src/refbox/refbox.cpp
This PR addresses a few issues that were bugging me in the past:
- Start the clips log as early as possible to not miss important logging steps
- Exit the clips environment after finalize so that a single sigint signal actually can shut down the refbox
- Shift logging of final stat tables to debug log to avoid malformed tables in frontend
- Properly reset the refbox by also resetting machine meta information and order related stuff
- Create new game reports if the refbox is reset
- When the refbox is put to PRE_GAME, it is a full reset (e.g., new field gets generated, orders get randomized etc), if it is put back to SETUP instead, then machine positions and order setup remains stable, so it is merely restarted.
This PR depends on https://github.com/robocup-logistics/rcll-refbox/pull/135, …
> cleanly start, terminate, reset and restart the refbox

- src/games/rcll/exploration.clp
- src/games/rcll/game.clp
- src/games/rcll/globals.clp
- src/games/rcll/net.clp
This PR addresses https://github.com/robocup-logistics/rcll-refbox/issues/144 by 
- re-setting the game if machine generation is not completed after 5 checks 
- sending machine related messages only after generation is completed
It is a new version of #145 which was based on a faulty branch.
> Machine generation fixes

- src/games/rcll/mongodb.clp
The bug fixed here (discoverd by @TarikViehmann) prevented the machine-generation from finishing when loading a map from a game report.
> Fix bug preventing machine generation from finishing when loading

- src/games/rcll/task-tracking.clp
Otherwise nasty side-effects can occur when placing workpieces down in quick succession at the same machine. As the refbox only updates the workpiece position (e.g., from input to output) once the processing step is advanced to processed.
Teams may in the meantime decide to start placing another product by aligning at the machine, hence sending a fresh agent task message before the input is actually cleared.
> Process agent tasks only once they actually ended

- cfg/game/default_game.yaml
- src/games/rcll/game.clp
- src/games/rcll/globals.clp
- src/games/rcll/machines.clp
- src/games/rcll/net.clp
- src/msgs/GameState.proto
Field size is variable according to the new rules but was not easy to configure. Additionally, teams often suffered from ill configured field sizes mismatching the actual size. This PR:
- makes field size easily configurable
- sends the field size to all teams via the GameState messages
> Make field size configurable and send it via GameState messages

- src/games/rcll/facts.clp
- src/games/rcll/game.clp
- src/games/rcll/orders.clp
- src/games/rcll/websocket.clp
- src/libs/websocket/data.cpp
- src/libs/websocket/data.h
- src/refbox/refbox.cpp
This PR addresses multiple issues related to the backend for the Webfrontend. In particular it:
- closes #163 by including field information in the game state
- addresses #164 (this will not be fixed, but the data is now sent periodically, which was a limitation before)
- closes #165 by including the "warning-sent" slot
- closes #168 by adding order information to points wherever it is available
> WS: Multiple additions to WS data

- src/games/rcll/robots.clp
- src/games/rcll/websocket.clp
- src/libs/websocket/data.cpp
- src/libs/websocket/data.h
- src/refbox/refbox.cpp
This PR addresses #171 and #172
Requires a fix in the refbox frontend for attention messages to be compatible due to a renamed field (see comment on #171 )
> Add game time to attention message, use phase time for maintenance

- src/games/rcll/production.clp
Previously, the machine instantly broke when recovering from a scheduled down time simply because the timeout for maximum length of the performed operation was crossed.
> update proc-start time after machine is up

- src/refbox/clips_logger.cpp
Error messages when the execution is halted do not end with \n but with .\n for some reason...
With this fix, the refbox will properly print error such as:
```
09:56:46.641570 C: [TMPLTDEF1] Invalid slot complexity not defined in corresponding deftemplate order
09:56:46.641764 C: [PRCCODE4] Execution halted during the actions of deffunction net-create-Order
09:56:46.641983 C: [PRCCODE4] Execution halted during the actions of deffunction net-create-OrderInfo
09:56:46.642147 C: [PRCCODE4] Execution halted during the actions of defrule net-send-OrderInfo
```
> clips-logger: also print buffer if line ends with .

- Dockerfile
- devcontainer.Dockerfile
There were 2 problems with the Dockerfile.
1. thrid-party repos were not enabled at final image, which caused the installation to fail.
2. the devcontainer only works with an arg, hence the build on quay failed due to no provided arg.
With the fixes to the above problem the containers build normally again:
https://quay.io/repository/robocup-logistics/rcll-refbox/build/2f575a61-122c-4568-a80d-6c595bf18cc0
> fix images not building on quay

- src/games/rcll/challenges.clp
- src/games/rcll/machines.clp
- src/libs/mps_placing_clips/mps_placing_clips.cpp
This PR superseedes https://github.com/robocup-logistics/rcll-refbox/pull/153.
~It is currently rooted on https://github.com/robocup-logistics/rcll-refbox/pull/180, which should be merged first.~
~Once the merge is done, this branch should further update the grasping challenge field layout.~
Original PR messages below:
The constraints actually express a cyan field (positive x axis). By placing these machines into the magenta halve, we break constraints for placement of input-only mps (the delivery station). This setup on side cyan (where left is a delivery station of ratation 180 and the right is any station with input and output side and rotation 90.
```
|`````| |    i    |
| i   | |         |
|_____| |    o    |
```
Adding them to the magenta sides results in the following illegal …
```
> do not shift cyan field to magenta.

- etc/scripts/drop_reports.bash
- etc/scripts/generate_benchmarks.bash
- src/games/rcll/globals.clp
- src/games/rcll/net.clp
Its quite annoying that VersionInfo can be missed, hence send it continuously, albeit with a low frequency.
> Improve sending of VersionInfo and migrate to mongodb 7 scripts

- src/games/rcll/challenges.clp
the free zones are just ZXY, why the machine zones are M_ZXY
> rcll: fix occupied zones being in wrong format

- src/libs/mps_comm/opcua/machine.cpp
- src/libs/mps_comm/opcua/machine.h
This hopefully prevents spurious crashes of the refbox if mashines are not connected.
> opcua: probe connection and port before attempting to connect via opcua

- src/games/rcll/production.clp
The proc-start is already increased by the down duratiom. when the machine goes down.
Increasing it again when it is coming up again is wrong.
> rcll: remove doubled proc-start increase on down

- src/games/rcll/mongodb.clp
- src/games/rcll/net.clp
Due to recent debugging sessions, we detected some bugs in the data pipeline.
One regards broken timestamps in agent task messages, the other is about wrongly assigned meta facts for machine histories.
> fix bugs in data pipeline

- src/games/rcll/game.clp
- src/games/rcll/mongodb.clp
The idea of this PR is to easily allow teams to build their own field setups, save them and load them again with improved frontend-sided reconfiguration.
The workflow to modify and save a field is as follows:
1) start a game regularly, including the setting of at least one team.
2) go to field view (pressing "watch" in the frontend) and move the field around to your liking per drag and drop
3) go to referee view again (pressing "referee" in the frontend)
4) change the config value "store-to-report" to a name of your choice in the "config" tab
The workflow to load the modified field is as follows:
1) start the refbox, but leave it in PRE-GAME (by not pressing "start-game")
2) change the config value "load-from-report" to the chosen name in the "config" tab
3) change the config value …
> improve dynamic field loading

- src/tools/rcll-prepare-machine.cpp
This fixes issues with the prepare machine scripts not terminating properly.
They are used by the frontend as well and caused annoying spam.
> prepare machine fix

- src/games/rcll/game.clp
This issue was introduced in [fefdec9ab](https://github.com/robocup-logistics/rcll-refbox/commit/fefdec9ab) where points were not correctly updated.
> game: repair pause not working properly
